### ISSUE TITLE
Add Javascript tests

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/groundwork#23]
As noted in https://github.com/wagtail/wagtail/discussions/7689#discussioncomment-2049777, this library doesn't have JS tests yet.

**Comment by chrisdevereux** [comment]
https://github.com/commonknowledge/groundwork/tree/main/frontend/geo/__tests__

It does, there just isn't much js yet, so not much to test!

**Comment by janbaykara** [comment]
Ah, seen. Sorry!
